#!/bin/bash
# File              : droidapps
# License           : MIT License
# Author            : M. Nabil Adani <nblid48[at]gmail[dot]com>
# Date              : Sabtu, 10/07/2021 09:44 WIB
# Last Modified Date: Sabtu, 10/07/2021 18:43 WIB
# Last Modified By  : M. Nabil Adani <nblid48[at]gmail[dot]com>

DMENU="rofi -dmenu -width 30 -i "

function sendMsg() {
    notify-send "Dmenu Scrcpy" "$1"
}

function getDevices() {
    amount=$(adb devices | awk '(NR > 1 && NF > 0) {print $1}' | wc -l)

    if (($amount < 2)); then
        adb get-serialno
    else
        adb devices | awk '(NR > 1 && NF > 0) {print $1}' | $DMENU
    fi

}

function getDisplayId() {
    adb -s $1 shell dumpsys display | grep mDisplayId | cut -d = -f 2 | $DMENU -mesg "Select display id" -lines 4 -p Display
}

function getPackage() {
    package=$(adb -s $1 shell pm list packages | cut -d : -f 2 | $DMENU -p "Application")
    if [ -z "${package}" ]; then
        sendMsg "No package selected"
    else
        activity=$(adb -s $1 shell dumpsys package $package | awk '/android.intent.action.MAIN:/{getline;print $2}')
        echo $activity
    fi

}

function startApps() {
    devices=$(getDevices)
    displayId=$(getDisplayId $devices)
    activity=$(getPackage $devices)

    adb -s $devices shell am start -n $activity --display $displayId
    scrcpy -s $devices --display $displayId
}

startApps
